import re

files = ["src/LandingPage.tsx", "src/PricingPage.tsx", "src/TermsAndPrivacy.tsx"]

def fix_content(c):
    # This regex looks for text between {lang === 'id' ? ' and ' : ' and '}
    c = c.replace("writer's", "writer\\'s")
    c = c.replace("don't", "don\\'t")
    c = c.replace("Don't", "Don\\'t")
    c = c.replace("it's", "it\\'s")
    c = c.replace("It's", "It\\'s")
    c = c.replace("you're", "you\\'re")
    c = c.replace("You're", "You\\'re")
    c = c.replace("we're", "we\\'re")
    c = c.replace("We're", "We\\'re")
    c = c.replace("they're", "they\\'re")
    c = c.replace("They're", "They\\'re")
    c = c.replace("that's", "that\\'s")
    c = c.replace("That's", "That\\'s")
    c = c.replace("let's", "let\\'s")
    c = c.replace("Let's", "Let\\'s")
    c = c.replace("we've", "we\\'ve")
    c = c.replace("We've", "We\\'ve")
    c = c.replace("I've", "I\\'ve")
    c = c.replace("you've", "you\\'ve")
    c = c.replace("You've", "You\\'ve")
    c = c.replace("they've", "they\\'ve")
    c = c.replace("They've", "They\\'ve")
    c = c.replace("I'm", "I\\'m")
    c = c.replace("I'll", "I\\'ll")
    c = c.replace("you'll", "you\\'ll")
    c = c.replace("You'll", "You\\'ll")
    c = c.replace("we'll", "we\\'ll")
    c = c.replace("We'll", "We\\'ll")
    c = c.replace("they'll", "they\\'ll")
    c = c.replace("They'll", "They\\'ll")
    c = c.replace("isn't", "isn\\'t")
    c = c.replace("Isn't", "Isn\\'t")
    c = c.replace("aren't", "aren\\'t")
    c = c.replace("Aren't", "Aren\\'t")
    c = c.replace("wasn't", "wasn\\'t")
    c = c.replace("Wasn't", "Wasn\\'t")
    c = c.replace("weren't", "weren\\'t")
    c = c.replace("Weren't", "Weren\\'t")
    c = c.replace("won't", "won\\'t")
    c = c.replace("Won't", "Won\\'t")
    c = c.replace("wouldn't", "wouldn\\'t")
    c = c.replace("Wouldn't", "Wouldn\\'t")
    c = c.replace("shouldn't", "shouldn\\'t")
    c = c.replace("Shouldn't", "Shouldn\\'t")
    c = c.replace("couldn't", "couldn\\'t")
    c = c.replace("Couldn't", "Couldn\\'t")
    c = c.replace("hasn't", "hasn\\'t")
    c = c.replace("Hasn't", "Hasn\\'t")
    c = c.replace("haven't", "haven\\'t")
    c = c.replace("Haven't", "Haven\\'t")
    c = c.replace("doesn't", "doesn\\'t")
    c = c.replace("Doesn't", "Doesn\\'t")
    c = c.replace("didn't", "didn\\'t")
    c = c.replace("Didn't", "Didn\\'t")
    c = c.replace("can't", "can\\'t")
    c = c.replace("Can't", "Can\\'t")
    c = c.replace("who's", "who\\'s")
    c = c.replace("Who's", "Who\\'s")
    c = c.replace("what's", "what\\'s")
    c = c.replace("What's", "What\\'s")
    c = c.replace("where's", "where\\'s")
    c = c.replace("Where's", "Where\\'s")
    c = c.replace("when's", "when\\'s")
    c = c.replace("When's", "When\\'s")
    c = c.replace("why's", "why\\'s")
    c = c.replace("Why's", "Why\\'s")
    c = c.replace("how's", "how\\'s")
    c = c.replace("How's", "How\\'s")
    c = c.replace("\\\\", "\\") # Fix double escaped
    return c

for f in files:
    with open(f, 'r') as file:
        content = file.read()
    content = fix_content(content)
    with open(f, 'w') as file:
        file.write(content)

